--- Data structures and reference values for the brook.rg module
---
---@module 'brook.rg.types'

--------------------------------------------------------------------------------

---@class brook.rg.ExecConfig
---
--- Maximum results before stopping (default: 1000, range 500-10,000)
---@field max_results integer
---
--- Maximum number of results to buffer before flushing (default: 100)
---@field max_batch_size integer
---
--- A decimal number, like 0.1, to add some jitter to the batch size, to make
--- the result stream look more organic (visible by the user via the quickfix
--- window counter in its statuline)
---@field batch_jitter number
---
--- A short time, in milliseconds, to give Neovim the opportunity to redraw
--- between batches (default: 10)
---@field flush_throttle_ms integer
---
--- Whether the quickfix list should be opened when results arrive (default: true)
---@field qf_open boolean
---
--- Whether the quickfix window should grow as results come in (default: true)
---@field qf_auto_resize boolean
---
--- Maximum height the quickfix window should grow to (when auto_resize is
--- enabled) or fixed height (when auto_resize is not enabled) (default: 10)
---@field qf_win_height number
---
--- Output format: 'one-line-per-match' or 'unique-lines'
---@field output_format brook.args.OutputFormat
---
--- Whether to set Vim's search register (/) with the pattern, enabling n/N
--- navigation and hlsearch (default: true)
---@field set_search_register boolean
---
--- Larger batches after ripgrep has finished (default: 10x max_batch_size)
---@field drain_phase_max_batch_size number
---
--- Less throttling after ripgrep has finished (default: 1)
---@field drain_phase_flush_throttle_ms number
---
--- Maximum number of characters to use for a result preview, to prevent
--- excessive memory use (default: 200, range: 100-500)
---@field max_preview_chars number
---
--- Print execution benchmark results (only for development, default: false)
---@field _benchmark boolean

--------------------------------------------------------------------------------

---@class brook.rg.RawOpts
---
--- A string representing raw command-line arguments
---@field args_string string
---
--- A fallback literal pattern to use when args_string doesn't include one
---@field fallback_word string
